#!/bin/bash
# Startup for the MiniMax H3 ComfyUI pod.
#
# Layout, deliberately different from the older pods: ComfyUI itself stays in
# the image at /app/comfyui and is never copied to the volume. Only mutable
# data (models, input, output, user settings, user-installed nodes) lives on
# the network volume. Updating ComfyUI is then just pulling a newer image tag,
# instead of being permanently shadowed by a stale copy on the volume.

set -e

COMFYUI_HOME=/app/comfyui
DATA_DIR="${COMFYUI_DATA_DIR:-/workspace/comfyui-data}"

echo "Starting ComfyUI pod (MiniMax H3)..."

# ---------------------------------------------------------------------------
# Network volume
# ---------------------------------------------------------------------------
NETWORK_VOLUME=false
if [ -d "/runpod-volume" ] && [ ! -e "/workspace" ]; then
    ln -sf /runpod-volume /workspace
    echo "[OK] Symlink created: /workspace -> /runpod-volume"
    NETWORK_VOLUME=true
elif [ -d "/workspace" ]; then
    NETWORK_VOLUME=true
    echo "[OK] Writable /workspace detected"
else
    mkdir -p /workspace
    echo "[WARN] No network volume - using container storage."
    echo "       MiniMax H3 needs up to 63 GB and will not fit here."
fi
export NETWORK_VOLUME

# NETWORK_VOLUME only means "something writable is mounted at /workspace" - it
# cannot tell a RunPod network volume from the host's local docker LV, and both
# look identical in the log. The difference is not cosmetic: local storage dies
# with the pod, so the 42 GB of weights and the Triton cache are re-paid on
# every deploy, and its ceiling is usually too low for a second model set.
# Print what it actually is and let the operator judge.
if [ "$NETWORK_VOLUME" = "true" ]; then
    df -h --output=source,fstype,size,avail /workspace 2>/dev/null | tail -1 | \
        while read -r src fstype size avail; do
            echo "     ${src}  ${fstype}  ${size} total, ${avail} free"
        done
    case "$(df --output=source /workspace 2>/dev/null | tail -1)" in
        *docker*|/dev/mapper/*|/dev/sd*|/dev/nvme*|overlay*)
            echo "     [NOTE] This looks like local pod storage, not a network"
            echo "            volume. Weights and the Triton cache will not"
            echo "            survive this pod." ;;
    esac
fi

mkdir -p "$DATA_DIR"/{models,input,output,user,custom_nodes}

# Triton JIT-compiles its kernels on first use and caches the result. Left in
# the container that cache dies with the pod, so every restart pays the
# recompile again. Measured on an RTX 5090: first sampling step 37.17s on a
# cold cache, 2.59s once warm - about 35s of one-off compilation. On the volume
# it is paid once, ever.
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$DATA_DIR/.triton}"
mkdir -p "$TRITON_CACHE_DIR"
mkdir -p "$DATA_DIR"/models/{diffusion_models,text_encoders,vae,loras,upscale_models,checkpoints}

# Ship the bundled upscaler onto the volume once, so it shows up alongside the
# user's own models rather than being split across two roots.
if [ -f "$COMFYUI_HOME/models/upscale_models/4x-UltraSharp.pth" ] && \
   [ ! -f "$DATA_DIR/models/upscale_models/4x-UltraSharp.pth" ]; then
    cp "$COMFYUI_HOME/models/upscale_models/4x-UltraSharp.pth" \
       "$DATA_DIR/models/upscale_models/" 2>/dev/null || true
fi

# Same idea for the bundled workflows: ComfyUI lists what is under
# --user-directory, which is on the volume, so a copy that stays in the image
# is invisible. Seeded once and never overwritten - an edited workflow belongs
# to the user, and a pod restart must not silently revert it.
mkdir -p "$DATA_DIR/user/default/workflows"
for wf in "$COMFYUI_HOME"/user/default/workflows/*.json; do
    [ -f "$wf" ] || continue
    target="$DATA_DIR/user/default/workflows/$(basename "$wf")"
    if [ ! -f "$target" ]; then
        cp "$wf" "$target" 2>/dev/null || true
        echo "[OK] Workflow seeded: $(basename "$wf")"
    fi
done

# ---------------------------------------------------------------------------
# Point ComfyUI at the volume. Regenerated on every boot so a changed
# COMFYUI_DATA_DIR takes effect without hand-editing a file on the volume.
# ---------------------------------------------------------------------------
cat > "$DATA_DIR/extra_model_paths.yaml" <<EOF
# Generated by start.sh on every boot - edits here are overwritten.
runpod_volume:
    base_path: ${DATA_DIR}
    is_default: true
    checkpoints: models/checkpoints
    diffusion_models: models/diffusion_models
    text_encoders: models/text_encoders
    clip: models/text_encoders
    vae: models/vae
    loras: models/loras
    upscale_models: models/upscale_models
    custom_nodes: custom_nodes
EOF
echo "[OK] extra_model_paths.yaml written to $DATA_DIR"

# ComfyUI imports custom nodes from the image AND from the volume path mapped
# just above. A pack present in both is imported twice; both copies register
# their frontend extensions under the same name and one wins arbitrarily. What
# you see is a JavaScript error while a workflow loads, several screens away
# from the cause. Name the collision here instead of letting it be debugged.
# Compared case-insensitively on purpose: the registry installs lowercase
# (comfyui-kjnodes) what the image clones in camel case (ComfyUI-KJNodes).
for vol in "$DATA_DIR"/custom_nodes/*/; do
    [ -d "$vol" ] || continue
    vol_name=$(basename "$vol")
    vol_key=$(printf '%s' "$vol_name" | tr '[:upper:]' '[:lower:]')
    for img in "$COMFYUI_HOME"/custom_nodes/*/; do
        [ -d "$img" ] || continue
        img_name=$(basename "$img")
        if [ "$(printf '%s' "$img_name" | tr '[:upper:]' '[:lower:]')" = "$vol_key" ]; then
            echo "[WARN] Custom node '${vol_name}' is installed twice:"
            echo "         image  ${img}"
            echo "         volume ${vol}"
            echo "       Both will load. Keep the image copy and drop the other:"
            echo "         rm -rf ${vol}"
        fi
    done
done

# The downloader writes to <COMFYUI_DIR>/models, so it must point at the volume.
export COMFYUI_DIR="$DATA_DIR"

# Diagnostics only - seconds, not minutes. Model acquisition is deliberately
# NOT here: it runs in the background once the services are listening. A fatal
# verdict (driver too old for this image's CUDA runtime) stops the pod here,
# instead of letting it look healthy and fail obscurely later.
echo "Running diagnostics..."
if ! bash /app/init.sh; then
    echo "[ERROR] Diagnostics failed - refusing to start. See the [FATAL] block above."
    exit 1
fi

# ---------------------------------------------------------------------------
# Optional SSH
# ---------------------------------------------------------------------------
if [ "${ENABLE_SSH:-false}" = "true" ]; then
    mkdir -p /var/run/sshd /etc/ssh/sshd_config.d

    # Host keys are stripped from the image at build time (see Dockerfile) and
    # created here instead, on the volume: they identify this deployment rather
    # than the image. Keeping them on the volume also makes them stable across
    # restarts, which matters - a fingerprint that changes on every boot trains
    # you to click through the warning that exists to be read.
    SSH_KEY_DIR="$DATA_DIR/ssh"
    mkdir -p "$SSH_KEY_DIR"
    chmod 700 "$SSH_KEY_DIR"
    if ls "$SSH_KEY_DIR"/ssh_host_*_key >/dev/null 2>&1; then
        cp "$SSH_KEY_DIR"/ssh_host_* /etc/ssh/
        echo "[OK] SSH host keys restored from $SSH_KEY_DIR"
    else
        ssh-keygen -A >/dev/null
        cp /etc/ssh/ssh_host_* "$SSH_KEY_DIR"/
        echo "[OK] SSH host keys generated for this deployment"
    fi
    chmod 600 /etc/ssh/ssh_host_*_key
    chmod 644 /etc/ssh/ssh_host_*_key.pub

    # Authentication. Without one of these, sshd runs and accepts connections
    # that nobody can complete: root ships with a locked password and the image
    # carries no authorized_keys.
    SSH_AUTH=""
    if [ -n "${PUBLIC_KEY}" ]; then
        mkdir -p /root/.ssh
        chmod 700 /root/.ssh
        printf '%s\n' "${PUBLIC_KEY}" >> /root/.ssh/authorized_keys
        # Restarts would otherwise append the same key over and over.
        sort -u /root/.ssh/authorized_keys -o /root/.ssh/authorized_keys
        chmod 600 /root/.ssh/authorized_keys
        SSH_AUTH="public key"
    fi
    if [ -n "${SSH_PASSWORD}" ]; then
        echo "root:${SSH_PASSWORD}" | chpasswd
        # Ubuntu's compiled-in default is PermitRootLogin prohibit-password, so
        # setting a password alone silently never works - which is what the
        # previous version of this block did. Enable it explicitly, and only
        # when a password was actually asked for.
        printf 'PermitRootLogin yes\nPasswordAuthentication yes\n' \
            > /etc/ssh/sshd_config.d/99-pod-password.conf
        SSH_AUTH="${SSH_AUTH:+$SSH_AUTH, }password"
        if [ -z "${PUBLIC_KEY}" ]; then
            echo "[WARN] Password auth on an exposed port 22. PUBLIC_KEY is safer."
        fi
    fi

    if [ -z "$SSH_AUTH" ]; then
        echo "[WARN] ENABLE_SSH=true but neither PUBLIC_KEY nor SSH_PASSWORD is set."
        echo "       sshd will listen, but no login can succeed. Set PUBLIC_KEY"
        echo "       (preferred) or SSH_PASSWORD - or set ENABLE_SSH=false."
    fi

    /usr/sbin/sshd -D &
    echo "[OK] SSH server started on port 22 (auth: ${SSH_AUTH:-none})"
fi

if [ -f "/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4" ]; then
    export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
    echo "[OK] tcmalloc enabled"
fi

# ---------------------------------------------------------------------------
# ComfyUI arguments
#
# Dynamic VRAM (comfy-aimdo) is what lets 42-63 GB of H3 weights run on a 32 GB
# card, and ComfyUI enables it by default on NVIDIA - so no --lowvram here,
# which would actively disable the better path.
#
# --fast-disk is OFF by default. It trades host RAM for disk, and pays off only
# with fast *local* NVMe. On the target pod (92 GB RAM) a workflow's weights fit
# in RAM outright, and the weights sit on a network volume rather than a local
# disk - so enabling it would slow things down twice over. Turn it on only on a
# RAM-starved pod.
# ---------------------------------------------------------------------------
COMFYUI_ARGS=(
    --listen 0.0.0.0
    --port "${COMFYUI_PORT}"
    --extra-model-paths-config "$DATA_DIR/extra_model_paths.yaml"
    --output-directory "$DATA_DIR/output"
    --input-directory "$DATA_DIR/input"
    --user-directory "$DATA_DIR/user"
    --preview-method "${PREVIEW_METHOD:-auto}"
)

# ComfyUI rejects any request carrying "Sec-Fetch-Site: cross-site" with a 403
# (server.py, create_origin_only_middleware). That is anti-CSRF protection for a
# localhost install, but behind the RunPod proxy it fires on the normal workflow
# - clicking the port link from the dashboard is, by definition, cross-site.
# --enable-cors-header REPLACES that middleware rather than adding to it.
# Pin CORS_ALLOW_ORIGIN to your pod URL to narrow it; "*" trades the CSRF
# protection for the dashboard link working.
if [ "${ENABLE_CORS:-true}" = "true" ]; then
    COMFYUI_ARGS+=(--enable-cors-header "${CORS_ALLOW_ORIGIN:-*}")
fi

# --- Performance levers, all opt-in and A/B testable without a rebuild ------
#
# CACHE_LRU: keep N node results. The log shows the 15 GB text encoder being
# re-staged on every prompt even when the text has not changed; caching the
# conditioning skips that entirely on repeat runs. Cheap here - the host has
# far more RAM than the working set.
[ -n "${CACHE_LRU}" ] && COMFYUI_ARGS+=(--cache-lru "${CACHE_LRU}")

# FAST_MODE: ComfyUI's --fast. Valid values are a space-separated subset of
# fp16_accumulation, fp8_matrix_mult, cublas_ops, autotune - or "all" for every
# one. Upstream calls these "untested and potentially quality deteriorating",
# so change one at a time and compare output, not just wall-clock.
if [ -n "${FAST_MODE}" ]; then
    if [ "${FAST_MODE}" = "all" ]; then
        COMFYUI_ARGS+=(--fast)
    else
        COMFYUI_ARGS+=(--fast ${FAST_MODE})
    fi
fi

# ASYNC_OFFLOAD_STREAMS: defaults to 2. A single run stages ~40 GB across
# PCIe, so offload bandwidth is a plausible bottleneck worth probing.
[ -n "${ASYNC_OFFLOAD_STREAMS}" ] && COMFYUI_ARGS+=(--async-offload "${ASYNC_OFFLOAD_STREAMS}")

# SAGE_ATTENTION: INT8-quantised attention, ~2x on the attention blocks. Off
# by default and deliberately: MiniMax H3 runs several layers in dtypes Sage
# refuses, and those fall back to PyTorch attention with a console message. The
# net gain on H3 is therefore not the advertised factor - it has to be measured
# at 0.88 MP, where attention dominates the clock, not at 0.4 MP where it does
# not. If the sageattention package is absent, ComfyUI says so and carries on.
[ "${SAGE_ATTENTION:-false}" = "true" ] && COMFYUI_ARGS+=(--use-sage-attention)

[ "${FAST_DISK:-false}" = "true" ] && COMFYUI_ARGS+=(--fast-disk)
[ -n "${VRAM_HEADROOM}" ] && COMFYUI_ARGS+=(--vram-headroom "${VRAM_HEADROOM}")
[ -n "${RESERVE_VRAM}" ] && COMFYUI_ARGS+=(--reserve-vram "${RESERVE_VRAM}")
# Escape hatch: anything else, e.g. "--disable-pinned-memory --cache-none".
[ -n "${COMFYUI_EXTRA_ARGS}" ] && COMFYUI_ARGS+=(${COMFYUI_EXTRA_ARGS})

start_code_server() {
    code-server \
        --bind-addr "0.0.0.0:${VSCODE_PORT}" \
        --auth none \
        --disable-telemetry \
        --disable-update-check \
        "$DATA_DIR" > /var/log/code-server.log 2>&1 &
    CODE_SERVER_PID=$!
}

start_comfyui() {
    cd "$COMFYUI_HOME"
    python main.py "${COMFYUI_ARGS[@]}" 2>&1 | tee /var/log/comfyui.log &
    COMFYUI_PID=$!
}

echo "Starting code-server on port ${VSCODE_PORT}..."
start_code_server
echo "[OK] code-server started (PID: $CODE_SERVER_PID)"

echo "Starting ComfyUI on port ${COMFYUI_PORT}..."
echo "     args: ${COMFYUI_ARGS[*]}"
start_comfyui
echo "[OK] ComfyUI started (PID: $COMFYUI_PID)"

# Weights land in the background, so a fresh volume no longer costs 15+ minutes
# of blind waiting. Progress goes to the pod log and to /var/log/models.log;
# ComfyUI lists each model as its file arrives, on the next UI refresh.
bash /app/fetch_models.sh 2>&1 | tee /var/log/models.log &
MODELS_PID=$!
echo "[OK] Model acquisition running in background (PID: $MODELS_PID)"
echo "     follow with: tail -f /var/log/models.log"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  VSCode:  http://0.0.0.0:${VSCODE_PORT}"
echo "  ComfyUI: http://0.0.0.0:${COMFYUI_PORT}"
[ "${ENABLE_SSH:-false}" = "true" ] && echo "  SSH:     port 22"
echo "  Data:    ${DATA_DIR}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

while true; do
    if ! kill -0 $CODE_SERVER_PID 2>/dev/null; then
        echo "[ERROR] code-server died, restarting..."
        start_code_server
    fi
    if ! kill -0 $COMFYUI_PID 2>/dev/null; then
        echo "[ERROR] ComfyUI died, restarting..."
        start_comfyui
    fi
    sleep 30
done
