#!/bin/bash
# Startup for the MiniMax H3 ComfyUI pod.
#
# Layout, deliberately different from the older pods: ComfyUI itself stays in
# the image at /app/comfyui and is never copied to the volume. Only mutable
# data (models, input, output, user settings, user-installed nodes) lives on
# the network volume. Updating ComfyUI is then just pulling a newer image tag,
# instead of being permanently shadowed by a stale copy on the volume.

set -e

COMFYUI_HOME=/app/comfyui
DATA_DIR="${COMFYUI_DATA_DIR:-/workspace/comfyui-data}"

echo "Starting ComfyUI pod (MiniMax H3)..."

# ---------------------------------------------------------------------------
# Network volume
# ---------------------------------------------------------------------------
NETWORK_VOLUME=false
if [ -d "/runpod-volume" ] && [ ! -e "/workspace" ]; then
    ln -sf /runpod-volume /workspace
    echo "[OK] Symlink created: /workspace -> /runpod-volume"
    NETWORK_VOLUME=true
elif [ -d "/workspace" ]; then
    NETWORK_VOLUME=true
    echo "[OK] Volume detected at /workspace"
else
    mkdir -p /workspace
    echo "[WARN] No network volume - using container storage."
    echo "       MiniMax H3 needs up to 63 GB and will not fit here."
fi
export NETWORK_VOLUME

mkdir -p "$DATA_DIR"/{models,input,output,user,custom_nodes}

# Triton JIT-compiles its kernels on first use and caches the result. Left in
# the container that cache dies with the pod, so every restart pays the
# recompile again. Measured on an RTX 5090: first sampling step 37.17s on a
# cold cache, 2.59s once warm - about 35s of one-off compilation. On the volume
# it is paid once, ever.
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$DATA_DIR/.triton}"
mkdir -p "$TRITON_CACHE_DIR"
mkdir -p "$DATA_DIR"/models/{diffusion_models,text_encoders,vae,loras,upscale_models,checkpoints}

# Ship the bundled upscaler onto the volume once, so it shows up alongside the
# user's own models rather than being split across two roots.
if [ -f "$COMFYUI_HOME/models/upscale_models/4x-UltraSharp.pth" ] && \
   [ ! -f "$DATA_DIR/models/upscale_models/4x-UltraSharp.pth" ]; then
    cp "$COMFYUI_HOME/models/upscale_models/4x-UltraSharp.pth" \
       "$DATA_DIR/models/upscale_models/" 2>/dev/null || true
fi

# ---------------------------------------------------------------------------
# Point ComfyUI at the volume. Regenerated on every boot so a changed
# COMFYUI_DATA_DIR takes effect without hand-editing a file on the volume.
# ---------------------------------------------------------------------------
cat > "$DATA_DIR/extra_model_paths.yaml" <<EOF
# Generated by start.sh on every boot - edits here are overwritten.
runpod_volume:
    base_path: ${DATA_DIR}
    is_default: true
    checkpoints: models/checkpoints
    diffusion_models: models/diffusion_models
    text_encoders: models/text_encoders
    clip: models/text_encoders
    vae: models/vae
    loras: models/loras
    upscale_models: models/upscale_models
    custom_nodes: custom_nodes
EOF
echo "[OK] extra_model_paths.yaml written to $DATA_DIR"

# The downloader writes to <COMFYUI_DIR>/models, so it must point at the volume.
export COMFYUI_DIR="$DATA_DIR"

# Diagnostics only - seconds, not minutes. Model acquisition is deliberately
# NOT here: it runs in the background once the services are listening. A fatal
# verdict (driver too old for this image's CUDA runtime) stops the pod here,
# instead of letting it look healthy and fail obscurely later.
echo "Running diagnostics..."
if ! bash /app/init.sh; then
    echo "[ERROR] Diagnostics failed - refusing to start. See the [FATAL] block above."
    exit 1
fi

# ---------------------------------------------------------------------------
# Optional SSH
# ---------------------------------------------------------------------------
if [ "${ENABLE_SSH:-false}" = "true" ]; then
    mkdir -p /var/run/sshd
    [ -n "$SSH_PASSWORD" ] && echo "root:$SSH_PASSWORD" | chpasswd
    /usr/sbin/sshd -D &
    echo "[OK] SSH server started on port 22"
fi

if [ -f "/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4" ]; then
    export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4
    echo "[OK] tcmalloc enabled"
fi

# ---------------------------------------------------------------------------
# ComfyUI arguments
#
# Dynamic VRAM (comfy-aimdo) is what lets 42-63 GB of H3 weights run on a 32 GB
# card, and ComfyUI enables it by default on NVIDIA - so no --lowvram here,
# which would actively disable the better path.
#
# --fast-disk is OFF by default. It trades host RAM for disk, and pays off only
# with fast *local* NVMe. On the target pod (92 GB RAM) a workflow's weights fit
# in RAM outright, and the weights sit on a network volume rather than a local
# disk - so enabling it would slow things down twice over. Turn it on only on a
# RAM-starved pod.
# ---------------------------------------------------------------------------
COMFYUI_ARGS=(
    --listen 0.0.0.0
    --port "${COMFYUI_PORT}"
    --extra-model-paths-config "$DATA_DIR/extra_model_paths.yaml"
    --output-directory "$DATA_DIR/output"
    --input-directory "$DATA_DIR/input"
    --user-directory "$DATA_DIR/user"
    --preview-method "${PREVIEW_METHOD:-auto}"
)

# ComfyUI rejects any request carrying "Sec-Fetch-Site: cross-site" with a 403
# (server.py, create_origin_only_middleware). That is anti-CSRF protection for a
# localhost install, but behind the RunPod proxy it fires on the normal workflow
# - clicking the port link from the dashboard is, by definition, cross-site.
# --enable-cors-header REPLACES that middleware rather than adding to it.
# Pin CORS_ALLOW_ORIGIN to your pod URL to narrow it; "*" trades the CSRF
# protection for the dashboard link working.
if [ "${ENABLE_CORS:-true}" = "true" ]; then
    COMFYUI_ARGS+=(--enable-cors-header "${CORS_ALLOW_ORIGIN:-*}")
fi

[ "${FAST_DISK:-false}" = "true" ] && COMFYUI_ARGS+=(--fast-disk)
[ -n "${VRAM_HEADROOM}" ] && COMFYUI_ARGS+=(--vram-headroom "${VRAM_HEADROOM}")
[ -n "${RESERVE_VRAM}" ] && COMFYUI_ARGS+=(--reserve-vram "${RESERVE_VRAM}")
# Escape hatch: anything else, e.g. "--disable-pinned-memory --cache-none".
[ -n "${COMFYUI_EXTRA_ARGS}" ] && COMFYUI_ARGS+=(${COMFYUI_EXTRA_ARGS})

start_code_server() {
    code-server \
        --bind-addr "0.0.0.0:${VSCODE_PORT}" \
        --auth none \
        --disable-telemetry \
        --disable-update-check \
        "$DATA_DIR" > /var/log/code-server.log 2>&1 &
    CODE_SERVER_PID=$!
}

start_comfyui() {
    cd "$COMFYUI_HOME"
    python main.py "${COMFYUI_ARGS[@]}" 2>&1 | tee /var/log/comfyui.log &
    COMFYUI_PID=$!
}

echo "Starting code-server on port ${VSCODE_PORT}..."
start_code_server
echo "[OK] code-server started (PID: $CODE_SERVER_PID)"

echo "Starting ComfyUI on port ${COMFYUI_PORT}..."
echo "     args: ${COMFYUI_ARGS[*]}"
start_comfyui
echo "[OK] ComfyUI started (PID: $COMFYUI_PID)"

# Weights land in the background, so a fresh volume no longer costs 15+ minutes
# of blind waiting. Progress goes to the pod log and to /var/log/models.log;
# ComfyUI lists each model as its file arrives, on the next UI refresh.
bash /app/fetch_models.sh 2>&1 | tee /var/log/models.log &
MODELS_PID=$!
echo "[OK] Model acquisition running in background (PID: $MODELS_PID)"
echo "     follow with: tail -f /var/log/models.log"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  VSCode:  http://0.0.0.0:${VSCODE_PORT}"
echo "  ComfyUI: http://0.0.0.0:${COMFYUI_PORT}"
[ "${ENABLE_SSH:-false}" = "true" ] && echo "  SSH:     port 22"
echo "  Data:    ${DATA_DIR}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

while true; do
    if ! kill -0 $CODE_SERVER_PID 2>/dev/null; then
        echo "[ERROR] code-server died, restarting..."
        start_code_server
    fi
    if ! kill -0 $COMFYUI_PID 2>/dev/null; then
        echo "[ERROR] ComfyUI died, restarting..."
        start_comfyui
    fi
    sleep 30
done
